Add function to set permissions
Addresses this error:

Traceback (most recent call last):
  File "/Users/henrybrent/Documents/GitHub/Uni Assignments/advent-of-code/venv/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 208, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './chromedriver'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/henrybrent/Documents/GitHub/Uni Assignments/advent-of-code/utils.py", line 540, in <module>
    main()
  File "/Users/henrybrent/Documents/GitHub/Uni Assignments/advent-of-code/utils.py", line 521, in main
    driver = init_webdriver()
             ^^^^^^^^^^^^^^^^
  File "/Users/henrybrent/Documents/GitHub/Uni Assignments/advent-of-code/utils.py", line 348, in init_webdriver
    driver = webdriver.Chrome(options=options, service=service)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/henrybrent/Documents/GitHub/Uni Assignments/advent-of-code/venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/henrybrent/Documents/GitHub/Uni Assignments/advent-of-code/venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 50, in __init__
    self.service.start()
  File "/Users/henrybrent/Documents/GitHub/Uni Assignments/advent-of-code/venv/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self._start_process(self._path)
  File "/Users/henrybrent/Documents/GitHub/Uni Assignments/advent-of-code/venv/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 230, in _start_process
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions.